//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  config: Config;
  configConnection: ConfigConnection;
  menuCategorie: MenuCategorie;
  menuCategorieConnection: MenuCategorieConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConfigArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConfigConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConfigFilter>;
};


export type QueryMenuCategorieArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMenuCategorieConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MenuCategorieFilter>;
};

export type DocumentFilter = {
  config?: InputMaybe<ConfigFilter>;
  menuCategorie?: InputMaybe<MenuCategorieFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Config | MenuCategorie | Folder;

export type ConfigEtablissement = {
  __typename?: 'ConfigEtablissement';
  nom?: Maybe<Scalars['String']['output']>;
  slogan?: Maybe<Scalars['String']['output']>;
  description1?: Maybe<Scalars['String']['output']>;
  description2?: Maybe<Scalars['String']['output']>;
  annee?: Maybe<Scalars['String']['output']>;
  localisation?: Maybe<Scalars['String']['output']>;
  noteGoogle?: Maybe<Scalars['String']['output']>;
  nombreAvis?: Maybe<Scalars['String']['output']>;
  anneesExistence?: Maybe<Scalars['String']['output']>;
};

export type ConfigContact = {
  __typename?: 'ConfigContact';
  adresse?: Maybe<Scalars['String']['output']>;
  telephone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  instagram?: Maybe<Scalars['String']['output']>;
  facebook?: Maybe<Scalars['String']['output']>;
  lienReservation?: Maybe<Scalars['String']['output']>;
  lienGoogleMaps?: Maybe<Scalars['String']['output']>;
  metro?: Maybe<Scalars['String']['output']>;
  parking?: Maybe<Scalars['String']['output']>;
};

export type ConfigHoraires = {
  __typename?: 'ConfigHoraires';
  jour?: Maybe<Scalars['String']['output']>;
  ouvert?: Maybe<Scalars['Boolean']['output']>;
  ouverture?: Maybe<Scalars['String']['output']>;
  fermeture?: Maybe<Scalars['String']['output']>;
};

export type ConfigAvis = {
  __typename?: 'ConfigAvis';
  note?: Maybe<Scalars['Float']['output']>;
  texte?: Maybe<Scalars['String']['output']>;
  auteur?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
};

export type ConfigImages = {
  __typename?: 'ConfigImages';
  hero?: Maybe<Scalars['String']['output']>;
  aboutPrincipale?: Maybe<Scalars['String']['output']>;
  aboutSecondaire?: Maybe<Scalars['String']['output']>;
  galerie?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ConfigStyle = {
  __typename?: 'ConfigStyle';
  couleurPrincipale?: Maybe<Scalars['String']['output']>;
  couleurSecondaire?: Maybe<Scalars['String']['output']>;
  nomDomaine?: Maybe<Scalars['String']['output']>;
};

export type Config = Node & Document & {
  __typename?: 'Config';
  etablissement?: Maybe<ConfigEtablissement>;
  contact?: Maybe<ConfigContact>;
  horaires?: Maybe<Array<Maybe<ConfigHoraires>>>;
  avis?: Maybe<Array<Maybe<ConfigAvis>>>;
  images?: Maybe<ConfigImages>;
  style?: Maybe<ConfigStyle>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ConfigEtablissementFilter = {
  nom?: InputMaybe<StringFilter>;
  slogan?: InputMaybe<StringFilter>;
  description1?: InputMaybe<StringFilter>;
  description2?: InputMaybe<StringFilter>;
  annee?: InputMaybe<StringFilter>;
  localisation?: InputMaybe<StringFilter>;
  noteGoogle?: InputMaybe<StringFilter>;
  nombreAvis?: InputMaybe<StringFilter>;
  anneesExistence?: InputMaybe<StringFilter>;
};

export type ConfigContactFilter = {
  adresse?: InputMaybe<StringFilter>;
  telephone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  instagram?: InputMaybe<StringFilter>;
  facebook?: InputMaybe<StringFilter>;
  lienReservation?: InputMaybe<StringFilter>;
  lienGoogleMaps?: InputMaybe<StringFilter>;
  metro?: InputMaybe<StringFilter>;
  parking?: InputMaybe<StringFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ConfigHorairesFilter = {
  jour?: InputMaybe<StringFilter>;
  ouvert?: InputMaybe<BooleanFilter>;
  ouverture?: InputMaybe<StringFilter>;
  fermeture?: InputMaybe<StringFilter>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ConfigAvisFilter = {
  note?: InputMaybe<NumberFilter>;
  texte?: InputMaybe<StringFilter>;
  auteur?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ConfigImagesFilter = {
  hero?: InputMaybe<ImageFilter>;
  aboutPrincipale?: InputMaybe<ImageFilter>;
  aboutSecondaire?: InputMaybe<ImageFilter>;
  galerie?: InputMaybe<ImageFilter>;
};

export type ConfigStyleFilter = {
  couleurPrincipale?: InputMaybe<StringFilter>;
  couleurSecondaire?: InputMaybe<StringFilter>;
  nomDomaine?: InputMaybe<StringFilter>;
};

export type ConfigFilter = {
  etablissement?: InputMaybe<ConfigEtablissementFilter>;
  contact?: InputMaybe<ConfigContactFilter>;
  horaires?: InputMaybe<ConfigHorairesFilter>;
  avis?: InputMaybe<ConfigAvisFilter>;
  images?: InputMaybe<ConfigImagesFilter>;
  style?: InputMaybe<ConfigStyleFilter>;
};

export type ConfigConnectionEdges = {
  __typename?: 'ConfigConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Config>;
};

export type ConfigConnection = Connection & {
  __typename?: 'ConfigConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ConfigConnectionEdges>>>;
};

export type MenuCategorieItems = {
  __typename?: 'MenuCategorieItems';
  nom?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  prix?: Maybe<Scalars['String']['output']>;
};

export type MenuCategorie = Node & Document & {
  __typename?: 'MenuCategorie';
  categorie?: Maybe<Scalars['String']['output']>;
  note?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<MenuCategorieItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type MenuCategorieItemsFilter = {
  nom?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  prix?: InputMaybe<StringFilter>;
};

export type MenuCategorieFilter = {
  categorie?: InputMaybe<StringFilter>;
  note?: InputMaybe<StringFilter>;
  items?: InputMaybe<MenuCategorieItemsFilter>;
};

export type MenuCategorieConnectionEdges = {
  __typename?: 'MenuCategorieConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<MenuCategorie>;
};

export type MenuCategorieConnection = Connection & {
  __typename?: 'MenuCategorieConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MenuCategorieConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateConfig: Config;
  createConfig: Config;
  updateMenuCategorie: MenuCategorie;
  createMenuCategorie: MenuCategorie;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateConfigArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfigMutation;
};


export type MutationCreateConfigArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfigMutation;
};


export type MutationUpdateMenuCategorieArgs = {
  relativePath: Scalars['String']['input'];
  params: MenuCategorieMutation;
};


export type MutationCreateMenuCategorieArgs = {
  relativePath: Scalars['String']['input'];
  params: MenuCategorieMutation;
};

export type DocumentUpdateMutation = {
  config?: InputMaybe<ConfigMutation>;
  menuCategorie?: InputMaybe<MenuCategorieMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  config?: InputMaybe<ConfigMutation>;
  menuCategorie?: InputMaybe<MenuCategorieMutation>;
};

export type ConfigEtablissementMutation = {
  nom?: InputMaybe<Scalars['String']['input']>;
  slogan?: InputMaybe<Scalars['String']['input']>;
  description1?: InputMaybe<Scalars['String']['input']>;
  description2?: InputMaybe<Scalars['String']['input']>;
  annee?: InputMaybe<Scalars['String']['input']>;
  localisation?: InputMaybe<Scalars['String']['input']>;
  noteGoogle?: InputMaybe<Scalars['String']['input']>;
  nombreAvis?: InputMaybe<Scalars['String']['input']>;
  anneesExistence?: InputMaybe<Scalars['String']['input']>;
};

export type ConfigContactMutation = {
  adresse?: InputMaybe<Scalars['String']['input']>;
  telephone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  instagram?: InputMaybe<Scalars['String']['input']>;
  facebook?: InputMaybe<Scalars['String']['input']>;
  lienReservation?: InputMaybe<Scalars['String']['input']>;
  lienGoogleMaps?: InputMaybe<Scalars['String']['input']>;
  metro?: InputMaybe<Scalars['String']['input']>;
  parking?: InputMaybe<Scalars['String']['input']>;
};

export type ConfigHorairesMutation = {
  jour?: InputMaybe<Scalars['String']['input']>;
  ouvert?: InputMaybe<Scalars['Boolean']['input']>;
  ouverture?: InputMaybe<Scalars['String']['input']>;
  fermeture?: InputMaybe<Scalars['String']['input']>;
};

export type ConfigAvisMutation = {
  note?: InputMaybe<Scalars['Float']['input']>;
  texte?: InputMaybe<Scalars['String']['input']>;
  auteur?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
};

export type ConfigImagesMutation = {
  hero?: InputMaybe<Scalars['String']['input']>;
  aboutPrincipale?: InputMaybe<Scalars['String']['input']>;
  aboutSecondaire?: InputMaybe<Scalars['String']['input']>;
  galerie?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ConfigStyleMutation = {
  couleurPrincipale?: InputMaybe<Scalars['String']['input']>;
  couleurSecondaire?: InputMaybe<Scalars['String']['input']>;
  nomDomaine?: InputMaybe<Scalars['String']['input']>;
};

export type ConfigMutation = {
  etablissement?: InputMaybe<ConfigEtablissementMutation>;
  contact?: InputMaybe<ConfigContactMutation>;
  horaires?: InputMaybe<Array<InputMaybe<ConfigHorairesMutation>>>;
  avis?: InputMaybe<Array<InputMaybe<ConfigAvisMutation>>>;
  images?: InputMaybe<ConfigImagesMutation>;
  style?: InputMaybe<ConfigStyleMutation>;
};

export type MenuCategorieItemsMutation = {
  nom?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  prix?: InputMaybe<Scalars['String']['input']>;
};

export type MenuCategorieMutation = {
  categorie?: InputMaybe<Scalars['String']['input']>;
  note?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<MenuCategorieItemsMutation>>>;
};

export type ConfigPartsFragment = { __typename: 'Config', etablissement?: { __typename: 'ConfigEtablissement', nom?: string | null, slogan?: string | null, description1?: string | null, description2?: string | null, annee?: string | null, localisation?: string | null, noteGoogle?: string | null, nombreAvis?: string | null, anneesExistence?: string | null } | null, contact?: { __typename: 'ConfigContact', adresse?: string | null, telephone?: string | null, email?: string | null, instagram?: string | null, facebook?: string | null, lienReservation?: string | null, lienGoogleMaps?: string | null, metro?: string | null, parking?: string | null } | null, horaires?: Array<{ __typename: 'ConfigHoraires', jour?: string | null, ouvert?: boolean | null, ouverture?: string | null, fermeture?: string | null } | null> | null, avis?: Array<{ __typename: 'ConfigAvis', note?: number | null, texte?: string | null, auteur?: string | null, date?: string | null } | null> | null, images?: { __typename: 'ConfigImages', hero?: string | null, aboutPrincipale?: string | null, aboutSecondaire?: string | null, galerie?: Array<string | null> | null } | null, style?: { __typename: 'ConfigStyle', couleurPrincipale?: string | null, couleurSecondaire?: string | null, nomDomaine?: string | null } | null };

export type MenuCategoriePartsFragment = { __typename: 'MenuCategorie', categorie?: string | null, note?: string | null, items?: Array<{ __typename: 'MenuCategorieItems', nom?: string | null, description?: string | null, prix?: string | null } | null> | null };

export type ConfigQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ConfigQuery = { __typename?: 'Query', config: { __typename: 'Config', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, etablissement?: { __typename: 'ConfigEtablissement', nom?: string | null, slogan?: string | null, description1?: string | null, description2?: string | null, annee?: string | null, localisation?: string | null, noteGoogle?: string | null, nombreAvis?: string | null, anneesExistence?: string | null } | null, contact?: { __typename: 'ConfigContact', adresse?: string | null, telephone?: string | null, email?: string | null, instagram?: string | null, facebook?: string | null, lienReservation?: string | null, lienGoogleMaps?: string | null, metro?: string | null, parking?: string | null } | null, horaires?: Array<{ __typename: 'ConfigHoraires', jour?: string | null, ouvert?: boolean | null, ouverture?: string | null, fermeture?: string | null } | null> | null, avis?: Array<{ __typename: 'ConfigAvis', note?: number | null, texte?: string | null, auteur?: string | null, date?: string | null } | null> | null, images?: { __typename: 'ConfigImages', hero?: string | null, aboutPrincipale?: string | null, aboutSecondaire?: string | null, galerie?: Array<string | null> | null } | null, style?: { __typename: 'ConfigStyle', couleurPrincipale?: string | null, couleurSecondaire?: string | null, nomDomaine?: string | null } | null } };

export type ConfigConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConfigFilter>;
}>;


export type ConfigConnectionQuery = { __typename?: 'Query', configConnection: { __typename?: 'ConfigConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ConfigConnectionEdges', cursor: string, node?: { __typename: 'Config', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, etablissement?: { __typename: 'ConfigEtablissement', nom?: string | null, slogan?: string | null, description1?: string | null, description2?: string | null, annee?: string | null, localisation?: string | null, noteGoogle?: string | null, nombreAvis?: string | null, anneesExistence?: string | null } | null, contact?: { __typename: 'ConfigContact', adresse?: string | null, telephone?: string | null, email?: string | null, instagram?: string | null, facebook?: string | null, lienReservation?: string | null, lienGoogleMaps?: string | null, metro?: string | null, parking?: string | null } | null, horaires?: Array<{ __typename: 'ConfigHoraires', jour?: string | null, ouvert?: boolean | null, ouverture?: string | null, fermeture?: string | null } | null> | null, avis?: Array<{ __typename: 'ConfigAvis', note?: number | null, texte?: string | null, auteur?: string | null, date?: string | null } | null> | null, images?: { __typename: 'ConfigImages', hero?: string | null, aboutPrincipale?: string | null, aboutSecondaire?: string | null, galerie?: Array<string | null> | null } | null, style?: { __typename: 'ConfigStyle', couleurPrincipale?: string | null, couleurSecondaire?: string | null, nomDomaine?: string | null } | null } | null } | null> | null } };

export type MenuCategorieQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MenuCategorieQuery = { __typename?: 'Query', menuCategorie: { __typename: 'MenuCategorie', id: string, categorie?: string | null, note?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'MenuCategorieItems', nom?: string | null, description?: string | null, prix?: string | null } | null> | null } };

export type MenuCategorieConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MenuCategorieFilter>;
}>;


export type MenuCategorieConnectionQuery = { __typename?: 'Query', menuCategorieConnection: { __typename?: 'MenuCategorieConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MenuCategorieConnectionEdges', cursor: string, node?: { __typename: 'MenuCategorie', id: string, categorie?: string | null, note?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'MenuCategorieItems', nom?: string | null, description?: string | null, prix?: string | null } | null> | null } | null } | null> | null } };

export const ConfigPartsFragmentDoc = gql`
    fragment ConfigParts on Config {
  __typename
  etablissement {
    __typename
    nom
    slogan
    description1
    description2
    annee
    localisation
    noteGoogle
    nombreAvis
    anneesExistence
  }
  contact {
    __typename
    adresse
    telephone
    email
    instagram
    facebook
    lienReservation
    lienGoogleMaps
    metro
    parking
  }
  horaires {
    __typename
    jour
    ouvert
    ouverture
    fermeture
  }
  avis {
    __typename
    note
    texte
    auteur
    date
  }
  images {
    __typename
    hero
    aboutPrincipale
    aboutSecondaire
    galerie
  }
  style {
    __typename
    couleurPrincipale
    couleurSecondaire
    nomDomaine
  }
}
    `;
export const MenuCategoriePartsFragmentDoc = gql`
    fragment MenuCategorieParts on MenuCategorie {
  __typename
  categorie
  note
  items {
    __typename
    nom
    description
    prix
  }
}
    `;
export const ConfigDocument = gql`
    query config($relativePath: String!) {
  config(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ConfigParts
  }
}
    ${ConfigPartsFragmentDoc}`;
export const ConfigConnectionDocument = gql`
    query configConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ConfigFilter) {
  configConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ConfigParts
      }
    }
  }
}
    ${ConfigPartsFragmentDoc}`;
export const MenuCategorieDocument = gql`
    query menuCategorie($relativePath: String!) {
  menuCategorie(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MenuCategorieParts
  }
}
    ${MenuCategoriePartsFragmentDoc}`;
export const MenuCategorieConnectionDocument = gql`
    query menuCategorieConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MenuCategorieFilter) {
  menuCategorieConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MenuCategorieParts
      }
    }
  }
}
    ${MenuCategoriePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      config(variables: ConfigQueryVariables, options?: C): Promise<{data: ConfigQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigQueryVariables, query: string}> {
        return requester<{data: ConfigQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigQueryVariables, query: string}, ConfigQueryVariables>(ConfigDocument, variables, options);
      },
    configConnection(variables?: ConfigConnectionQueryVariables, options?: C): Promise<{data: ConfigConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigConnectionQueryVariables, query: string}> {
        return requester<{data: ConfigConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigConnectionQueryVariables, query: string}, ConfigConnectionQueryVariables>(ConfigConnectionDocument, variables, options);
      },
    menuCategorie(variables: MenuCategorieQueryVariables, options?: C): Promise<{data: MenuCategorieQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MenuCategorieQueryVariables, query: string}> {
        return requester<{data: MenuCategorieQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MenuCategorieQueryVariables, query: string}, MenuCategorieQueryVariables>(MenuCategorieDocument, variables, options);
      },
    menuCategorieConnection(variables?: MenuCategorieConnectionQueryVariables, options?: C): Promise<{data: MenuCategorieConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MenuCategorieConnectionQueryVariables, query: string}> {
        return requester<{data: MenuCategorieConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MenuCategorieConnectionQueryVariables, query: string}, MenuCategorieConnectionQueryVariables>(MenuCategorieConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/1.6/content/dummy/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  